# 全局信息
title: "博久游戏"

# 开发dev  测试test 上线 pro
active: dev

# 日志配置
log:
  path: "./logs"
  prefix: "hall"   # 日志文件前缀
  level: "debug"    # 日志级别：debug/info/error/warn
  development: true  # 是否为开发者模式
  debugFileSuffix: "debug.log"  # debug日志文件后缀
  warnFileSuffix: "warn.log"    # warn日志文件后缀
  errorFileSuffix: "error.log"   # error日志文件后缀
  infoFileSuffix: "info.log"    # info日志文件后缀
  maxAge: 2        # 保存的最大天数
  maxBackups: 3000  # 最多存在多少个切片文件
  maxSize: 10  # 日日志文件大小（M）

# grpc 协议
ser:
  etcdServer: ["127.0.0.1:2379"]
  grpc:
    stream:
     host: "127.0.0.1"
     port: 18089
     regKey: "/hall/stream"
    unitary:
     host: "127.0.0.1"
     port: 18089
     regKey: "/hall/Unitary"
  #http:
  #  https:
  #    host: "127.0.0.1"
  #    port: 18043
  #    regKey: "/hall/stream"
  #  http:
  #    host: "127.0.0.1"
  #    port: 18023
  #    regKey: "/hall/stream"

mysql-master:
  addr: "192.168.0.188"
  port: 3306
  username: "root"
  password: "root"
  database: "bj_server"

mysql-slave1:
  addr: "192.168.0.188"
  port: 3306
  username: "root"
  password: "root"
  database: "bj_server"

mysql-log-master:
  addr: "192.168.0.188"
  port: 3306
  username: "root"
  password: "root"
  database: "bj_log"

mysql-log-slave1:
  addr: "192.168.0.188"
  port: 3306
  username: "root"
  password: "root"
  database: "bj_log"

mongod-master:
  addr: "127.0.0.1"
  port: 27017
  dbname: "bojiu"
  username: ""
  password: ""

mongod-slave1:
  addr: "127.0.0.1"
  port: 27017
  dbname: "bojiu"
  username: ""
  password: ""

redis:
  addr: "192.168.0.188:6379"
  password: ""
  DB: 3
  poolSize: 30
  minIdleConns: 30

country:
  - short: "CN"
    name: "中国"
    en: "China"
    label: "+86 中国"
    value: "86"
  - short: "IN"
    name: "印度"
    en: "UnitedArabEmirates"
    label: "+51 印度"
    value: "971"
  - short: "VT"
    name: "越南"
    en: "UnitedArabEmirates"
    label: "+51 越南"
    value: "971"